### ISSUE TITLE
VSCode intellisense does not work for custom matchers

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-sdk-testing#6]
### Expected behavior

Intellisense should work when using matchers in consumer unit tests.

### Actual behavior

The matchers do not show up in VSCode's autocomplete menu when typing.

### Steps to reproduce

Add this import to the top of a spec:

```
import { expect } from '@skyux-sdk/testing';
```

Type an expectation and wait for the autocomplete menu to appear. None of the SKY UX matchers show up:

<img width="609" alt="screen shot 2018-12-06 at 9 21 41 am" src="https://user-images.githubusercontent.com/12497062/49589819-5d15e180-f938-11e8-93fc-ec12c2996a62.png">

**Comment by Blackbaud-IanThomas** [comment]
Can we make a note about how it's also not showing the default jasmine matchers?

**Comment by Blackbaud-KrisMahon** [comment]
@blackbaud/skyux-maintainers I think I have a solution for this extremely annoying issue.  I have added the following file to my team's SPA with good results so far (I found several broken unit tests that were immediately highlighted just by having full types available), and I'd like to add similar code to this library.  This code surfaces the types for both the jasmine matchers and the custom Sky matchers.

```typescript
const windowRef: any = window;

/**
 * Interface to surface the Sky custom matchers.
 * See:  https://github.com/blackbaud/skyux-sdk-testing/blob/master/src/app/public/matchers/matchers.ts
 */
export interface SkyMatchers<T> extends jasmine.Matchers<T> {
  not: SkyMatchers<T>;
  toBeAccessible(): void;
  toBeVisible(): void;
  toExist(): void;
  toHaveCssClass(expectedClassName: string): void;
  toHaveStyle(expectedStyles: any): void;
  toHaveText(expectedText: string, trimWhitespace?: boolean): void;
  toEqualResourceText(name: string, args: { name: string, args: any[] }, callback?: () => void): void;
  toHaveResouceText(name: string, args: { name: string, args: any[] }, trimWhitespace?: boolean, callback?: () => void): void;
}

/**
 * Create an expectation for a spec.
 * @param actual Actual computed value to test expectations against.
 */
export function expect<T>(actual: T): SkyMatchers<T> {
  return windowRef.expect(actual);
}
```

**Comment by Blackbaud-PaulCrowder** [comment]
Sounds good. Where would this code be added? Would this change anything about how consumers currently import `expect` into their tests?

**Comment by Blackbaud-KrisMahon** [comment]
I'm playing with it now, and looks like I can add it directly to the `matchers.ts` file (exactly as I have above) where the custom matchers live.  All tests are passing locally.  If consumers are currently importing this `expect` method from SKYUX, then nothing will need to change for them after updating the lib version.

**Comment by Blackbaud-KrisMahon** [comment]
PR #25 is available for review
